import React, { Component } from 'react';
import { withRouter } from 'react-router-dom';
import { compose } from 'recompose';

import { withFirebase } from '../../Firebase';
import { AuthUserContext } from '../../Session';

import BookedTripCard from './BookedTripCard';

const INITIAL_STATE = {
  user: null,
  trips: [],
  gotContext: false,
  error: null,
};

/** @class BookedTripsItem representing a trip and its firebase key. */
class BookedTripsItem {
 /**
 * Creates an instance of BookedTripsItem.
 *
 * @constructor
 * @param trip {Trip} The trip generated by our algorithm.
 * @param key {String} The firebase key associated with the trip.
 */
  constructor(trip, key) {
    this.trip = trip;
    this.key = key;
  }
}

/** @class BookedTripsBase that handles the main rendering the the Booked Trips tab */
class BookedTripsBase extends Component {
  /**
  * Creates an instance of BookedTripsBase.
  *
  * @constructor
  * @param props {props} The react Component properties.
  */
  constructor(props) {
    super(props);
    this.state = { ...INITIAL_STATE };
  }

  /**
  * Sets the state of the object's rendered variables.
  *
  * @param none
  * @return none
  */
  componentDidUpdate() {
    if (typeof this.context.authUser !== 'undefined' && this.context.authUser !== null && !this.state.gotContext) {
      this.hello = this.context;
      this.setState({ gotContext: true });
      this.refreshBookedTrips(this.hello.authUser);
    }
  }

  /**
  * Gets all of the booked trips
  *
  * @param tripIds {Array<Int>} IDs of trips to be obtained from FireBase
  * @return Promise {Promise} A Promise that will eventually return each trip from FireBase.
  */
  getAllBookedTrips(tripIds) {
    const tripRef = this.props.firebase.bookedTrip;
    return Promise.all(
      tripIds.map(function(tripId) {
        return new Promise(function(resolve, reject) {
          try {    
            tripRef(tripId).on("value", function(snapshot, prevChildKey) {
              if (typeof snapshot.val().name === 'undefined') {
                resolve(null);
              } else {
                var newTrip = snapshot.val();
                resolve(newTrip);
              }
            })
          } catch (e) {
            reject(e)
          }
        })
      })
    );
  }
  
  /**
  * Gets all of the booked trip IDs
  *
  * @param userId {String} ID of user to be sent to FireBase
  * @return Promise {Promise} A Promise that will eventually return each tripID from FireBase.
  */
  getUserBookedTripIds(userId) {
    const currentUserTripsRef = this.props.firebase.singleUserBookedTrips(userId);
    return new Promise(function (resolve, reject) {
      try {
        currentUserTripsRef.on("value", function(snapshot, prevChildKey) {
            if (typeof snapshot.val() === 'undefined') {
              resolve(null);
            } else {
              var userTrips = snapshot.val();
              resolve({
                userTrips: userTrips,
              });
            }
        })
      } catch (e) {
          reject(e)
      }
    });
  }

  /**
  * Gets the user's booked trips
  *
  * @param authUser {authUser} Object representing a logged in user.
  * @return Promise {Promise} A Promise that will eventually return each trip from FireBase.
  */
  getUserBookedTrips(authUser) {
    const getAllBookedTrips = ((tripIds) => this.getAllBookedTrips(tripIds));
    const getUserBookedTripIds = ((uid) => this.getUserBookedTripIds(uid));
    
    return new Promise(function (resolve, reject) {
      getUserBookedTripIds(authUser.uid).then(function (result) {
        if (typeof result.userTrips !== 'undefined' && result.userTrips !== null) {
          let userTrips = [];
          // userTrips is all the user's tripIds
          for (const [key, tripId] of Object.entries(result.userTrips)) {
            userTrips.push(tripId);
          }
          const tripPromises = getAllBookedTrips(userTrips);
          tripPromises.then(function (values) {
            resolve(values)
          }).catch(function (error) {
            resolve(null);
            console.log('debug: ', error);
          });
        }
      }).catch(function (error) {
        resolve(null);
        console.log('debug: ', error);
      });
    });
  }

  /**
  * Sets all of the booked trips
  *
  * @param trips {Array<BookedTripsItem>} trips obtained from FireBase
  * @return none
  */
  setBookedTrips(trips) {
    if (typeof trips === 'undefined' || trips !== null) {
      var tripItems = [];
      for (const trip of trips) {
        var tripItem = new BookedTripsItem(trip, tripItems.length);
        tripItems.push(tripItem);
      }
      this.setState({
        trips: tripItems,
      });
    }
  }

  /**
  * Gets all of the booked trips for a certain user
  *
  * @param authUser {authUser} Object representing a logged in user
  * @return None
  */
  refreshBookedTrips(authUser) {
    if (typeof authUser !== 'undefined' && authUser) {
      var setBookedTrips_c = ((trips) => this.setBookedTrips(trips));
      this.getUserBookedTrips(authUser).then(function (result) {
        setBookedTrips_c(result);
      });
    }
    else {
      console.log('debug: ', 'auth user still null');
    }
  }

  /**
  * Renders the component
  *
  * @param none
  * @return {HTML} The HTML of the rendered component
  */
  render() {
    return(
      <div>
        <div>
          {(this.state.trips || []).map(listItem => (
            <div key={listItem.key} style={{padding: 25}}>
              <BookedTripCard trip={listItem.trip}/>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

BookedTripsBase.contextType = AuthUserContext;

const BookedTrips = compose(
  withRouter,
  withFirebase,
)(BookedTripsBase);

export default BookedTrips;